--------------------------------------------------------
--  File created - Sunday-January-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTO
--------------------------------------------------------

  CREATE TABLE "PIM"."AUTO" 
   (	"ID_AUTO" NUMBER, 
	"MARKA" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"KUBIKAZA" VARCHAR2(20 BYTE), 
	"GODISTE" VARCHAR2(20 BYTE), 
	"BOJA" VARCHAR2(20 BYTE), 
	"CENA" VARCHAR2(20 BYTE), 
	"VLASNIK" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IZNAJMLJENO
--------------------------------------------------------

  CREATE TABLE "PIM"."IZNAJMLJENO" 
   (	"EMAIL_IZNAJMIOCA" VARCHAR2(30 BYTE), 
	"AUTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KORISNIK
--------------------------------------------------------

  CREATE TABLE "PIM"."KORISNIK" 
   (	"IME" VARCHAR2(20 BYTE), 
	"PREZIME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"LOZINKA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VLASNICI
--------------------------------------------------------

  CREATE TABLE "PIM"."VLASNICI" 
   (	"ID_VLASNIK" NUMBER, 
	"PREZIME" VARCHAR2(20 BYTE), 
	"IME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PIM.AUTO
SET DEFINE OFF;
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (1,'Audi','A2','1400','2005','crna','120',1);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (2,'Audi','A3','1500','2010','crvena','210',2);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (3,'bmw','316','1995','2009','sivi','190',1);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (4,'bmw','x3','2100','2013','crni','250',2);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (5,'volvo','v50','1800','2010','zeleni','140',1);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (6,'volvo','xc 70','2300','2011','zuti','180',2);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (7,'kia','optima','1700','2013','beli','175',1);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (8,'lamborghini','aventador','6300','2014','crvena','380',2);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (9,'ford','escort','1800','2008','plava','130',1);
Insert into PIM.AUTO (ID_AUTO,MARKA,MODEL,KUBIKAZA,GODISTE,BOJA,CENA,VLASNIK) values (10,'ford','fiesta','1500','2014','siva','170',1);
REM INSERTING into PIM.IZNAJMLJENO
SET DEFINE OFF;
REM INSERTING into PIM.KORISNIK
SET DEFINE OFF;
Insert into PIM.KORISNIK (IME,PREZIME,EMAIL,LOZINKA) values ('olivera','mladenovic','oliveram1996@gmail.com','12345');
Insert into PIM.KORISNIK (IME,PREZIME,EMAIL,LOZINKA) values ('milan','pizurica','milan123@gmail.com','11111');
REM INSERTING into PIM.VLASNICI
SET DEFINE OFF;
Insert into PIM.VLASNICI (ID_VLASNIK,PREZIME,IME) values (1,'maric','marko');
Insert into PIM.VLASNICI (ID_VLASNIK,PREZIME,IME) values (2,'peric','petar');
--------------------------------------------------------
--  DDL for Index AUTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIM"."AUTO_PK" ON "PIM"."AUTO" ("ID_AUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KORISNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIM"."KORISNIK_PK" ON "PIM"."KORISNIK" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VLASNICI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIM"."VLASNICI_PK" ON "PIM"."VLASNICI" ("ID_VLASNIK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AUTO
--------------------------------------------------------

  ALTER TABLE "PIM"."AUTO" MODIFY ("VLASNIK" NOT NULL ENABLE);
  ALTER TABLE "PIM"."AUTO" ADD CONSTRAINT "AUTO_PK" PRIMARY KEY ("ID_AUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIM"."AUTO" MODIFY ("ID_AUTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IZNAJMLJENO
--------------------------------------------------------

  ALTER TABLE "PIM"."IZNAJMLJENO" MODIFY ("AUTO" NOT NULL ENABLE);
  ALTER TABLE "PIM"."IZNAJMLJENO" MODIFY ("EMAIL_IZNAJMIOCA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KORISNIK
--------------------------------------------------------

  ALTER TABLE "PIM"."KORISNIK" ADD CONSTRAINT "KORISNIK_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIM"."KORISNIK" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VLASNICI
--------------------------------------------------------

  ALTER TABLE "PIM"."VLASNICI" ADD CONSTRAINT "VLASNICI_PK" PRIMARY KEY ("ID_VLASNIK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIM"."VLASNICI" MODIFY ("ID_VLASNIK" NOT NULL ENABLE);
